version = "1.0"

[main]
name.en = "DumbBudget configuration"
name.fr = "Configuration de DumbBudget"
services = ["__APP__"]

    [main.config]
    name.en = "Configuration Options"
    name.fr = "Options de configuration"

        [main.config.currency]
        ask.en = "Currency code"
        ask.fr = "Code devise"
        type = "select"
        choices = ["USD", "EUR", "GBP", "CHF", "CNY", "JPY"]
        help.en = "Choose the currency code for transactions"
        help.fr = "Choisir le code devise pour les transactions"
        bind = "CURRENCY:__INSTALL_DIR__/.env"

        [main.config.pin]
        ask.en = "PIN protection"
        ask.fr = "Protection par code PIN"
        type = "number"
        help.en = "Choose an optional PIN protection (4-10 digits)"
        help.fr = "Choisissez la protection par code PIN en option (4 à 10 chiffres)"
        bind = "DUMBBUDGET_PIN:__INSTALL_DIR__/.env"
