#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.currency = "EUR"
    args.pin = "1234"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.ed7cff438ff06ab677796e35cfee79fd4ff8089f.name = "Upgrade from 2025.03.12~ynh1"
